// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNqvnIsB6p93kDOicOYVBir51sErZ5qX4',
    appId: '1:1039203314951:web:369653cad9a5d433d3a9a2',
    messagingSenderId: '1039203314951',
    projectId: 'buzzify-1a726',
    authDomain: 'buzzify-1a726.firebaseapp.com',
    storageBucket: 'buzzify-1a726.firebasestorage.app',
    measurementId: 'G-P367CNL025',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhw3uFJOAprJYIufEhC6zVyzYy5y8ZizA',
    appId: '1:1039203314951:android:61e01d2db598c4d1d3a9a2',
    messagingSenderId: '1039203314951',
    projectId: 'buzzify-1a726',
    storageBucket: 'buzzify-1a726.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyzE6RBpj0SfCgPn5IW_vNwk0RVm9o7AA',
    appId: '1:1039203314951:ios:af74a2d17c3c8492d3a9a2',
    messagingSenderId: '1039203314951',
    projectId: 'buzzify-1a726',
    storageBucket: 'buzzify-1a726.firebasestorage.app',
    iosBundleId: 'com.example.buzzify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyzE6RBpj0SfCgPn5IW_vNwk0RVm9o7AA',
    appId: '1:1039203314951:ios:af74a2d17c3c8492d3a9a2',
    messagingSenderId: '1039203314951',
    projectId: 'buzzify-1a726',
    storageBucket: 'buzzify-1a726.firebasestorage.app',
    iosBundleId: 'com.example.buzzify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCNqvnIsB6p93kDOicOYVBir51sErZ5qX4',
    appId: '1:1039203314951:web:90fa9a6a4d170826d3a9a2',
    messagingSenderId: '1039203314951',
    projectId: 'buzzify-1a726',
    authDomain: 'buzzify-1a726.firebaseapp.com',
    storageBucket: 'buzzify-1a726.firebasestorage.app',
    measurementId: 'G-M46L8ZC9VP',
  );
}
